### ISSUE TITLE
Simplify the CSS code for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [THOM3121/prj-rev-bwfs-dasmoto#5]
When there are shared properties for multiple selectors, it is usually a good idea to simplify the code by applying the property to them at once. The font-family and font-weight properties are shared by multiple selectors, which can be simplified like so

```css
h1, h2, #price {
  font-family: Helvetica;
  font-weight: bold;
}
```
